def getEvent(event):
    return {
        0:"Zone OK",
        1:"Zone open",
        2:"Partition status",
        3:"Bell status",
        6:"Non-reportable event",
        12:"Cold start wireless zone",
        13:"Cold start wireless module",
        14:"Bypass programming",
        15:"User code activated output",
        16:"Wireless smoke maintenance signal",
        17:"Delay zone alarm transmission",
        18:"Zone signal strength weak 1",
        19:"Zone signal strength weak 2",
        20:"Zone signal strength weak 3",
        21:"Zone signal strength weak 4",
        24:"Fire delay started",
        26:"Software access",
        27:"Bus module event",
        28:"StayD pass acknowledged",
        29:"Arming with user",
        30:"Special arming",
        31:"Disarming with user",
        32:"Disarming after an alarm with user",
        33:"Alarm cancelled with user",
        34:"Special disarming",
        35:"Zone bypassed",
        36:"Zone in alarm",
        37:"Fire alarm",
        38:"Zone alarm restore",
        39:"Fire alarm restore",
        40:"Special alarm",
        41:"Zone shutdown",
        42:"Zone tampered",
        43:"Zone tamper restore",
        44:"New trouble",
        45:"Trouble restored",
        46:"Bus/EBus/wireless module new trouble",
        47:"Bus/EBus/wireless module trouble restored",
        48:"Special",
        49:"Low battery on zone",
        50:"Low battery on zone restore",
        51:"Zone supervision trouble",
        52:"Zone supervision restore",
        53:"Wireless module supervision trouble",
        54:"Wireless module supervision restore",
        55:"Wireless module tamper trouble",
        56:"Wireless module tamper restore",
        57:"Non-medical alarm",
        58:"Zone forced",
        59:"Zone included",
        60:"Remote low battery",
        61:"Remote low battery restore",
        64:"System status"
        }.get(event,"")